[package]
name = "nmea"
version = "0.0.8"
authors = ["Felix Obenhuber <felix@obenhuber.de>", "Evgeniy A. Dushistov <dushistov@mail.ru>"]
description = "Simple NMEA 0183 parser"
license = "Apache-2.0"
keywords = ["NMEA", "gps", "glonass", "coordinate", "position"]
repository = "https://github.com/Dushistov/rust-nmea"
documentation = "https://docs.rs/nmea/"
readme = "README.md"
edition = "2018"

[dependencies]
nom = "5"
chrono = "0.4"

[dev-dependencies]
quickcheck = "0.9"
approx = "0.3"

[badges]
travis-ci = { repository = "Dushistov/rust-nmea" }
appveyor = { repository = "Dushistov/rust-nmea" }